[tool.poetry]
name = "text-dedup"
version = "0.3.0"
description = "All-in-one text deduplication"
authors = ["Chenghao Mou <mouchenghao@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
packages = [{include = "text_dedup"}]

[tool.poetry.dependencies]
python = "^3.8,<3.12"
#numpy = "^1.23.2"
tqdm = "^4.64.1"
datasets = "^2.4.0"
rich = "^12.5.1"
scipy = "1.9.1"
xxhash = "^3.0.0"
pybloom-live = "^4.0.0"
bitarray = "^2.6.2"
dask = {extras = ["bag"], version = "^2023.1.0"}
#pyspark = "^3.3.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
coverage = "^6.4.4"
Sphinx = "^5.1.1"
furo = "^2022.6.21"
pre-commit = "^2.20.0"
isort = "^5.10.1"
livereload = "^2.6.3"
sphinx-copybutton = "^0.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
max-line-length = 120
